name: Pipeline

on:
  push:
    branches: [main]
    workflow_dispatch:
    schedule: {cron: "0 0 * * *"}
    pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: nix develop . --command -- bash -e {0}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-dev-build-v1-${{ hashFiles('mix.lock', 'flake.lock') }}
          path: |
            deps
            _build
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          mix do deps.get
          mix dialyzer
          mix credo
          mix test
